=== BLE-LTER/eml/lib/datamanager/schema/dataquery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="eml://ecoinformatics.org/dataquery"
    targetNamespace="eml://ecoinformatics.org/dataquery">
    
    <xs:element name="dataquery">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="union" type="unionType"/>
                    <xs:element name="query" type="queryType"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="unionType">
        <xs:sequence>
            <xs:element name="query" type="queryType"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="queryType">
        <xs:sequence>
            <xs:element name="selection" type="selectionType" maxOccurs="unbounded"/>
            <xs:element name="where" type="whereType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="selectionType">
        <xs:sequence>
            <xs:element name="datapackage" type="datapackageType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="whereType">
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="condition" type="conditionType" minOccurs="0"/>
                    <xs:element name="or" type="logicalRelationType" minOccurs="0"/>
                    <xs:element name="and" type="logicalRelationType" minOccurs="0"/>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="logicalRelationType">
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="condition" type="conditionType" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="or" type="whereType" minOccurs="0"/>
                    <xs:element name="and" type="whereType" minOccurs="0"/>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="conditionType">
        <xs:sequence>
            <xs:element name="left" type="conditionMemberType"/>
            <xs:element name="right" type="conditionMemberType"/>
            <xs:element name="operator" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="conditionMemberType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="datapackage" type="datapackageType"/>
                <xs:element name="value" type="xs:string"/>
                <xs:element name="subquery" type="queryType"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="datapackageType">
        <xs:sequence>
            <xs:element name="entity" type="entityType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="entityType">
        <xs:sequence>
            <xs:element name="attribute" type="attributeType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="index" type="xs:int"/>
        <xs:attribute name="id" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="attributeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="pathexpr" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="index" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>
    
    
    
    
    
</xs:schema>

=== BLE-LTER/eml/lib/datamanager/schema/dataquery.xml
<?xml version="1.0"?>
<!-- sample data query specification instance for the datamanager library -->
<dq:dataquery 
	xmlns:dq="eml://ecoinformatics.org/dataquery" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="eml://ecoinformatics.org/dataquery dataquery.xsd ">
	<union>
		<query>
			<selection>
				<datapackage id="leinfelder.1.1">
					<entity id="">
						<attribute index="0"></attribute>
					</entity>
					<!-- For metadata items -->
					<entity id="leinfelder.1.1">
						<attribute index="0">
							<name>id</name>
							<pathexpr>assessment/@id</pathexpr>
						</attribute>
						<attribute index="1">
							<name>title</name>
							<pathexpr>assessment/@title</pathexpr>
						</attribute>
						<attribute index="2">
							<name>type</name>
							<pathexpr>assessment/@type</pathexpr>
						</attribute>
					</entity>
					<!-- dataTable items in same package-->
					<entity id="table_1">
						<attribute index="0" />
						<attribute index="1" />
						<attribute index="2" />
					</entity>
				</datapackage>
				<!-- query across datapackages -->
				<datapackage id="leinfelder.2.1">
					<entity id="table_1">
						<attribute index="0" />
					</entity>
				</datapackage>
			</selection>
			<where>
				<and>
					<!-- joins -->
					<!--metadata to data-->
					<condition>
						<left>
							<datapackage id="leinfelder.1.1">
								<entity id="leinfelder.1.1">
									<attribute index="0" />
								</entity>
							</datapackage>
						</left>
						<right>
							<datapackage id="leinfelder.1.1">
								<entity id="table_1">
									<attribute index="0" />
								</entity>
							</datapackage>
						</right>
						<operator>EQUALS</operator>
					</condition>
					<!-- data to additional data (in different datapackage) -->
					<condition>
						<left>
							<datapackage id="leinfelder.1.1">
								<entity id="table_1">
									<attribute index="0" />
								</entity>
							</datapackage>
						</left>
						<right>
							<datapackage id="leinfelder.2.1">
								<entity id="table_1">
									<attribute index="0" />
								</entity>
							</datapackage>
						</right>
						<operator>EQUALS</operator>
					</condition>
					<!-- subquery -->
					<condition>
						<left>
							<datapackage id="leinfelder.1.1">
								<entity id="table_1">
									<attribute index="1" />
								</entity>
							</datapackage>
						</left>
						<right>
							<subquery>
								<selection>
									<datapackage id="">
										<entity id="">
											<attribute index="0"/>
										</entity>
									</datapackage>
								</selection>
							</subquery>
						</right>
						<operator>NOT IN</operator>
					</condition>
					<!--compound value comparision -->
					<or>
						<condition>
							<left>
								<datapackage id="leinfelder.1.1">
									<entity id="table_1">
										<attribute index="1" />
									</entity>
								</datapackage>
							</left>
							<right>
								<value>%grande%</value>
							</right>
							<operator>LIKE</operator>
						</condition>
						<condition>
							<left>
								<datapackage id="leinfelder.1.1">
									<entity id="table_1">
										<attribute index="1" />
									</entity>
								</datapackage>
							</left>
							<right>
								<value>%venti%</value>
							</right>
							<operator>LIKE</operator>
						</condition>
					</or>
					
				</and>
			</where>
		</query>
	</union>
</dq:dataquery>
